app = "deutschifytelegram"
primary_region = "fra"

[env]
  PORT = "8080"
  FLY_APP_NAME = "deutschifytelegram"
  OPENAI_API_KEY = "${OPENAI_API_KEY}"
  TELEGRAM_BOT_TOKEN = "${TELEGRAM_BOT_TOKEN}"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  # Removed the 'processes' field as Docker manages the startup command

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/"
    protocol = "http"
    grace_period = "5s"
    restart_limit = 0